# Generated by Django 3.2.14 on 2022-12-19 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='basket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baskets.basket'),
        ),
    ]
