# Generated by Django 3.2.14 on 2022-12-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_orders_basket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='basket_id',
        ),
    ]
