# Generated by Django 3.2.14 on 2022-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0004_remove_orders_basket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
