# Generated by Django 3.2.14 on 2022-12-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0006_auto_20221223_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
