# Generated by Django 3.2.14 on 2022-12-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('index', models.PositiveIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
        ),
    ]
