# Generated by Django 3.2.14 on 2022-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_static1',
            field=models.ImageField(blank=True, null=True, upload_to='products_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_static2',
            field=models.ImageField(blank=True, null=True, upload_to='products_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_static3',
            field=models.ImageField(blank=True, null=True, upload_to='products_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_static_shop',
            field=models.ImageField(blank=True, null=True, upload_to='products_image'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
