# Generated by Django 3.2.14 on 2023-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20221230_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=400),
        ),
    ]
