# Generated by Django 3.2.14 on 2023-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_address',
            field=models.TextField(default=1203),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_eaddress',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_name',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_pn',
            field=models.CharField(default=321, max_length=20),
            preserve_default=False,
        ),
    ]
