# Generated by Django 3.2.14 on 2023-02-07 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221230_1613'),
        ('order', '0004_auto_20230203_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_eaddress',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_pn',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
